import { jsPDF } from 'jspdf';
import autoTableModule from 'jspdf-autotable';
import ExcelJS from 'exceljs';

const autoTable = autoTableModule.default || autoTableModule;

export async function sendExcel(res, filename, rows) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'LabOS';
  const worksheet = workbook.addWorksheet('LabOS');
  const columns = Object.keys(rows[0] || { Notice: 'No records matched this report.' });

  worksheet.columns = columns.map((key) => ({
    header: key,
    key,
    width: Math.min(Math.max(key.length + 4, 14), 36)
  }));
  rows.forEach((row) => worksheet.addRow(row));
  worksheet.getRow(1).font = { bold: true };

  const buffer = Buffer.from(await workbook.xlsx.writeBuffer());
  res.setHeader('Content-Disposition', `attachment; filename="${filename}.xlsx"`);
  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  res.send(buffer);
}

export function sendPdf(res, filename, title, columns, rows, options = {}) {
  const doc = new jsPDF({ orientation: 'landscape' });
  doc.setFontSize(16);
  doc.text(title, 14, 16);
  doc.setFontSize(9);
  doc.text(`Generated by LabOS on ${new Date().toLocaleString('en-KE')}`, 14, 23);
  let startY = 30;
  if (options.summaryLines?.length) {
    options.summaryLines.forEach((line, index) => doc.text(line, 14, 30 + index * 5));
    startY = 36 + options.summaryLines.length * 5;
  } // LabOS fix: printable/PDF filing reports can include MOH-style facility and stock-out summaries.
  autoTable(doc, { head: [columns], body: rows, startY, styles: { fontSize: 8 } });
  const buffer = Buffer.from(doc.output('arraybuffer'));
  res.setHeader('Content-Disposition', `attachment; filename="${filename}.pdf"`);
  res.setHeader('Content-Type', 'application/pdf');
  res.send(buffer);
}
